var json = [

{symbol: "a",     description :"letra"},
{symbol: "b",     description :"letra"},
{symbol: "c",     description :"letra"},
{symbol: "d",     description :"letra"},
{symbol: "e",     description :"letra"},
{symbol: "f",     description :"letra"},
{symbol: "g",     description :"letra"},
{symbol: "h",     description :"letra"},
{symbol: "i",     description :"letra"},
{symbol: "j",     description :"letra"},
{symbol: "k",     description :"letra"},
{symbol: "l",     description :"letra"},
{symbol: "m",     description :"letra"},
{symbol: "n",     description :"letra"},
{symbol: "o",     description :"letra"},
{symbol: "p",     description :"letra"},
{symbol: "q",     description :"letra"},
{symbol: "r",     description :"letra"},
{symbol: "s",     description :"letra"},
{symbol: "t",     description :"letra"},
{symbol: "x",     description :"letra"},
{symbol: "y",     description :"letra"},
{symbol: "z",     description :"letra"},
{symbol: "A",     description :"letra"},
{symbol: "B",     description :"letra"},
{symbol: "C",     description :"letra"},
{symbol: "D",     description :"letra"},
{symbol: "E",     description :"letra"},
{symbol: "F",     description :"letra"},
{symbol: "G",     description :"letra"},
{symbol: "H",     description :"letra"},
{symbol: "I",     description :"letra"},
{symbol: "J",     description :"letra"},
{symbol: "K",     description :"letra"},
{symbol: "L",     description :"letra"},
{symbol: "M",     description :"letra"},
{symbol: "N",     description :"letra"},
{symbol: "O",     description :"letra"},
{symbol: "P",     description :"letra"},
{symbol: "Q",     description :"letra"},
{symbol: "E",     description :"letra"},
{symbol: "S",     description :"letra"},
{symbol: "T",     description :"letra"},
{symbol: "W",     description :"letra"},
{symbol: "X",     description :"letra"},
{symbol: "Y",     description :"letra"},
{symbol: "Z",     description :"letra"},
{symbol: "w",     description :"letra"},
{symbol: "0",     description :"numero"},
{symbol: "1",     description :"numero"},
{symbol: "2",     description :"numero"},
{symbol: "3",     description :"numero"},
{symbol: "4",     description :"numero"},
{symbol: "5",     description :"numero"},
{symbol: "6",     description :"numero"},
{symbol: "7",     description :"numero"},
{symbol: "8",     description :"numero"},
{symbol: "9",     description :"numero"},
{symbol: "/",     description :"operador"},
{symbol: "*",     description :"operador"},
{symbol: "-",     description :"operador"},
{symbol: "+",     description :"operador"},
{symbol: "=",     description :"operador"},
{symbol: "<",     description :"operador"},
{symbol: ">",     description :"operador"},
{symbol: "(",     description :"separador"},
{symbol: ")",     description :"separador"},
{symbol: "[",     description :"separador"},
{symbol: "]",     description :"separador"},
{symbol: "{",     description :"separador"},
{symbol: "}",     description :"separador"},
{symbol: "!",     description :"especial"},
{symbol: "@",     description :"especial"},
{symbol: "#",     description :"especial"},
{symbol: "$",     description :"especial"},
{symbol: "&",     description :"especial"},
{symbol: "-",     description :"especial"},
{symbol: "_",     description :"especial"},
{symbol: ",",     description :"especial"},
{symbol: ".",     description :"especial"},
{symbol: ";",     description :"especial"},
{symbol: ":",     description :"especial"},
{symbol: "\n",     description :"especial"},










];