var jsonW = [
	{word: "program",		description: "simple", 		contador: 0 },
	{word: "begin",		    description: "simple", 		contador: 0 },
	{word: "end",			description: "simple", 		contador: 0 },
	{word: "var",			description: "simple", 		contador: 0 },
	{word: "as",			description: "simple", 		contador: 0 },
	{word: "integer",		description: "simple", 		contador: 0 },
	{word: "string",		description: "simple", 		contador: 0 },
	{word: "double",		description: "simple", 		contador: 0 },
	{word: "float",		    description: "simple", 		contador: 0 },
	{word: "boolean",		description: "simple", 		contador: 0 },
	{word: "true",			description: "simple", 		contador: 0 },
	{word: "false",		    description: "simple", 		contador: 0 },
	{word: "and",			description: "simple", 		contador: 0 },
	{word: "or",			description: "simple", 		contador: 0 },
	{word: "not",			description: "simple", 		contador: 0 },
	{word: "print",		    description: "simple", 		contador: 0 },
	{word: "if",			description: "compose", 	contador: 0 },
	{word: "else",			description: "compose", 	contador: 0 },
	{word: "elseif",		description: "compose", 	contador: 0 },
	{word: "endif",		    description: "compose", 	contador: 0 },
	{word: "for",			description: "compose", 	contador: 0 },
	{word: "endfor",		description: "compose", 	contador: 0 },
	{word: "do",			description: "compose", 	contador: 0 },
	{word: "enddo",		    description: "compose", 	contador: 0 },
	{word: "while",		    description: "compose", 	contador: 0 },
	{word: "endwhile",		description: "compose", 	contador: 0 },
	{word: "switch",		description: "compose", 	contador: 0 },
	{word: "case",			description: "compose", 	contador: 0 },
	{word: "endswitch",	    description: "compose", 	contador: 0 },
	{word: "initmat",		description: "compose", 	contador: 0 },
	{word: "endmat",		description: "compose", 	contador: 0 },
	// { word: "&amp;&amp;",description: "compose",		contador: 0 },
	// { word: "/*",		description: "compose", 	contador: 0 },
	// { word: "*/",		description: "compose", 	contador: 0 },
	// { word: ":=",		description: "compose", 	contador: 0 },
	// { word: "||",		description: "compose",	 	contador: 0 },
	// { word: "!",			description: "compose", 	contador: 0 }
];